# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190821_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
